version: '3'
services:
  webm_db:
    image: mongo:4.2.1
    restart: always
    volumes:
      - webm-db-data:/data/db
      - webm-db-config:/data/configdb
  webm_monitor:
    build: 
      dockerfile: Dockerfile
      context: ../
    restart: always
    environment:
      - ENV_FOR_DYNACONF=production
    links:
      - webm_db
    depends_on:
      - webm_db
volumes:
  webm-db-data:
  webm-db-config: