[default]
DB_URL = 'localhost'
DB_PORT = 27017
DB_NAME = 'webm_stock'

DB_COLLECTION_TEST = 'test'
DB_API_RESPONSES = 'api_responses'
DB_THREADS = 'threads'
DB_FILES = 'files'

BOARD_MONITOR_DELAY_SECONDS = 60
THREAD_MONITOR_THREAD_REQUEST_DELAY_SECONDS = 5
THREAD_FAIL_COUNT_LIMIT = 5
FILE_MEDIA_EXTENSIONS = '.webm .mp4'

BOARD_URL = 'https://2ch.hk/b/threads.json'
THREAD_URL = 'https://2ch.hk/b/res/{}.json'

[production]
DB_URL = 'webm_db'
THREAD_MONITOR_THREAD_REQUEST_DELAY_SECONDS = 2
