DB_URL = 'localhost'
DB_PORT = 27017
DB_NAME = 'webm_stock'
DB_COLLECTION_TEST = 'test'
DB_API_RESPONSES = 'api_responses'
DB_THREADS = 'threads'
BOARD_MONITOR_DELAY_SECONDS = 5 
THREAD_MONITOR_THREAD_REQUEST_DELAY_SECONDS = 10;   
